data_ingestion_config:
  data_ingestion_dir: "data_ingestion"
  ingestion_dataset_file_name: "ingested_data.csv"
  stock_symbol: "TATASTEEL.NS"

data_preprocessing_config:
  data_preprocessing_dir: "data_preprocessing"
  preprocessing_dataset_file_name: "preprocessed_data.csv"

data_processing_config:
  data_processing_dir: "data_processing"
  processing_dataset_file_name: "processed_data.csv"
  processing_data_moving_averages_dir: "moving_averages"
  fifty_moving_avg_file: "fifty_moving_average.csv"
  hundred_moving_avg_file: "hundred_moving_average.csv"
  two_hundred_moving_avg_file: "two_hundred_moving_average.csv"
  data_processing_graphs_dir: "graphs"
  close_price_graph_file_name: "close_price.html"
  50ma_graph_file_name: "50ma.html"
  100ma_graph_file_name: "100ma.html"
  200ma_graph_file_name: "200ma.html"
  close_50_100_200_ma_comp_graph_file_name: "ma_comparision.html"

model_training_config:
  model_train_data_file_name: "train_data.csv"
  model_test_data_file_name: "test_data.csv"
  model_file_name: "model.keras"
  model_data_dir: 'model_data'
  model_training_data_dir: "model_training"
  
model_prediction_config:
  model_prediction_data_dir: "model_prediction"
  model_prediction_graphs_dir: "graphs"
  model_prediction_predicted_graph_file_name: "prediction_graph.html"


training_pipeline_config:
  pipeline_name: "stock_trend_prediction"
  artifact_dir: "artifact"