data_ingestion_config:
  data_ingestion_dir: "data_ingestion"
  ingestion_dataset_file_name: "ingested_data.csv"
  stock_symbol: "TATAMOTORS.NS"

data_preprocessing_config:
  data_preprocessing_dir: "data_preprocessing"
  preprocessing_dataset_file_name: "preprocessed_data.csv"

data_processing_config:
  data_processing_dir: "data_processing"
  processing_dataset_file_name: "processed_data.csv"
  processing_data_moving_averages_dir: "moving_averages"
  fifty_moving_avg_file: "fifty_moving_average.csv"
  hundred_moving_avg_file: "hundred_moving_average.csv"
  two_hundred_moving_avg_file: "two_hundred_moving_average.csv"
  graphs_file_name: "graphs.png"

model_training_config:
  model_train_data_file_name: "train_data.csv"
  model_test_data_file_name: "test_data.csv"
  model_file_name: "model.h5"
  

training_pipeline_config:
  pipeline_name: "stock_trend_prediction"
  artifact_dir: "artifact"